# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_sim <- function(RSim) {
    .Call(`_posim_do_sim`, RSim)
}

start_profiler <- function(str) {
    .Call(`_posim_start_profiler`, str)
}

stop_profiler <- function() {
    .Call(`_posim_stop_profiler`)
}

